name: patrol_devtools_extension
description: A new Flutter project.
publish_to: none

version: 0.1.0

environment:
  sdk: '>=3.3.0-91.0.dev <4.0.0'
  flutter: 3.16.0-0.3.pre

dependencies:
  collection: ^1.18.0
  cupertino_icons: ^1.0.6
  devtools_app_shared: 0.0.7
  devtools_extensions: 0.0.10
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.3
  json_annotation: ^4.8.1
  vm_service: 13.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  leancode_lint: ^7.0.0+1

flutter:
  uses-material-design: true
