name: patrol_devtools_extension
description: A new Flutter project.
publish_to: none

version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: '>=3.13.0' # actually it should be the next stable after 3.13

dependencies:
  cupertino_icons: ^1.0.6
  devtools_app_shared: ^0.0.6
  devtools_extensions: ^0.0.9
  devtools_shared: ^4.1.0
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.3
  json_annotation: ^4.6.0
  vm_service: ^13.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  leancode_lint: ^6.0.0

flutter:
  uses-material-design: true
