name: patrol prepare

on:
  push:
    branches: [master, develop]
    tags-ignore: ['*']
    paths:
      - 'packages/patrol/**'
  pull_request:
    branches: [master, develop]
    paths:
      - 'packages/patrol/**'

jobs:
  prepare-android-on-windows:
    runs-on: windows-latest
    name: Android on Windows

    defaults:
      run:
        working-directory: packages/patrol/example/android

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

      - name: Generate Gradle wrapper
        working-directory: packages/patrol/example
        run: flutter build apk --debug --flavor=does-not-exist || true

      - name: ktlint check
        run: .\gradlew.bat :patrol:ktlintCheck

      - name: ktlint format
        run: .\gradlew.bat :patrol:ktlintFormat

      - name: Build app with Gradle
        run: .\gradlew.bat :app:assembleDebug

      - name: Build app with Flutter tool
        run: flutter build apk --debug

  prepare-android-on-linux:
    runs-on: ubuntu-latest
    name: Android on Linux

    defaults:
      run:
        working-directory: packages/patrol/example/android

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Generate Gradle wrapper
        working-directory: packages/patrol/example
        run: flutter build apk --debug --flavor=does-not-exist || true

      - name: Run unit tests
        if: success() || failure()
        run: ./gradlew :patrol:testDebug

      - name: ktlint check
        if: success() || failure()
        run: ./gradlew :patrol:ktlintCheck

      - name: ktlint format
        if: success() || failure()
        run: ./gradlew :patrol:ktlintFormat

      - name: Build example app with Gradle
        run: ./gradlew :app:assembleDebug

      - name: Build example app with Flutter tool
        run: flutter build apk --debug

  prepare-ios:
    runs-on: macos-13
    name: iOS on macOS

    defaults:
      run:
        working-directory: packages/patrol/ios

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: brew update
        run: brew update

      - name: brew install swift-format
        run: brew install swift-format

      - name: brew install clang-format
        run: brew install clang-format

      # Disabled because of generated protobuf code
      #- name: swift-format lint
      #  run: test -z $(swift-format lint --recursive --strict .)

      - name: swift-format format
        run: |
          swift-format format --recursive --in-place .
          git update-index --refresh
          git diff-index --quiet HEAD --

      - name: clang-format
        run: |
          find . -iname '*.h' -o -iname '*.m' | xargs -I {} clang-format --dry-run --Werror {}

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.x'

      - name: Generate iOS build files
        working-directory: packages/patrol/example
        run: flutter build ios --config-only

      - name: Start iOS simulator
        uses: futureware-tech/simulator-action@v2
        with:
          model: iPhone 14
          os: iOS
          os_version: 16.2
          erase_before_boot: true
          shutdown_after_job: true

      - name: Run unit tests
        working-directory: packages/patrol/example/ios
        run: |
          xcodebuild test \
            -workspace Runner.xcworkspace \
            -scheme Runner \
            -only-testing RunnerTests \
            -configuration Debug \
            -sdk iphoneos -destination 'platform=iOS Simulator,name=iPhone 14' \
            -derivedDataPath ../build/ios_unit \
            -quiet \

  prepare-flutter:
    name: Flutter ${{ matrix.flutter-version }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        flutter-version: ['3.3.x', '3.7.x', '3.10.x']

    defaults:
      run:
        working-directory: packages/patrol

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ matrix.flutter-version }}

      - name: flutter pub get
        run: flutter pub get

      - name: flutter test
        if: always()
        run: flutter test --coverage

      - name: flutter analyze
        if: always()
        run: flutter analyze

      - name: dart format
        if: always()
        run: dart format --set-exit-if-changed .

      - name: flutter pub publish --dry-run
        if: always()
        run: flutter pub publish --dry-run

      - name: flutter pub get (example app)
        if: always()
        working-directory: ./packages/patrol/example
        run: flutter pub get

      - name: dart format (example app)
        if: always()
        working-directory: ./packages/patrol/example
        run: dart format --set-exit-if-changed .

      - name: flutter analyze (example app)
        if: always()
        working-directory: ./packages/patrol/example
        run: flutter analyze

      - name: flutter test (example app)
        if: always()
        working-directory: ./packages/patrol/example
        run: flutter test
